[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate --schema=prisma/schema.prisma && chmod +x start.sh"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
